### ISSUE TITLE
CMU Preprocessed Dataset

### ISSUE THREAD

**Issue by anas-zafar** [Samleo8/learnable-triangulation-pytorch#6]
Great work @Samleo8 ! Is it possible of you could share the preprocessed data of the cmu panoptic dataset? Thanks

**Comment by anas-zafar** [comment]
@Samleo8 I am having this issue while trying to generate labels for the cmu dataset. Could you please guide me how to resolve this? Thanks
Traceback (most recent call last):
  File "generate-labels-npy.py", line 421, in <module>
    retval['table'] = np.concatenate(retval['table'])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by fxyQAQ** [comment]
Hello, have you solved the problem? How did you use detectron2 to pre-process the video?
